import "./SecurityAlerts.css";
import { useEffect, useState } from "react";
import axios from "axios";

function SecurityAlerts() {

    const [alerts, setAlerts] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {

        const loadSecurityAlerts = async () => {

            try {

                const token = localStorage.getItem("token");

                const response = await axios.get(
                    "https://securevault-backend-lo1o.onrender.com/api/security/alerts",
                    {
                        headers: {
                            Authorization: `Bearer ${token}`
                        }
                    }
                );

                setAlerts(response.data);

            } catch (error) {

                console.error(
                    "Failed to load security alerts:",
                    error
                );

            } finally {

                setLoading(false);

            }
        };

        loadSecurityAlerts();

    }, []);

    return (

        <div className="security-alerts-page">

            {/* HEADER */}

            <div className="security-alerts-header">

                <div>

                    <h1>Security Alerts</h1>

                    <p>
                        Review security alerts generated by
                        suspicious activities.
                    </p>

                </div>

                <div className="alerts-summary">

                    <div className="alerts-summary-icon">
                        🚨
                    </div>

                    <div>

                        <span>Total Alerts</span>

                        <strong>
                            {alerts.length}
                        </strong>

                    </div>

                </div>

            </div>


            {/* CARD */}

            <div className="security-alerts-card">

                <div className="security-alerts-card-header">

                    <div>

                        <h2>Recent Security Alerts</h2>

                        <p>
                            Monitor alerts generated by the
                            security monitoring system.
                        </p>

                    </div>

                    <div className="alerts-count">

                        {alerts.length}{" "}

                        {alerts.length === 1
                            ? "Alert"
                            : "Alerts"}

                    </div>

                </div>


                {/* LOADING */}

                {loading ? (

                    <div className="alerts-state">

                        <div className="loading-spinner"></div>

                        <span>
                            Loading security alerts...
                        </span>

                    </div>

                ) : alerts.length === 0 ? (

                    /* EMPTY */

                    <div className="alerts-state">

                        <div className="empty-icon">
                            🛡️
                        </div>

                        <strong>
                            No Security Alerts
                        </strong>

                        <span>
                            No security alerts have been generated yet.
                        </span>

                    </div>

                ) : (

                    /* TABLE */

                    <div className="alerts-table-wrapper">

                        <table className="security-alerts-table">

                            <thead>

                                <tr>

                                    <th>EMAIL</th>
                                    <th>ALERT TYPE</th>
                                    <th>MESSAGE</th>
                                    <th>SEVERITY</th>
                                    <th>CREATED AT</th>
                                    <th>STATUS</th>

                                </tr>

                            </thead>

                            <tbody>

                                {alerts.map((alert, index) => (

                                    <tr
                                        key={
                                            alert.id ||
                                            index
                                        }
                                    >

                                        {/* EMAIL */}

                                        <td>

                                            <div className="email-cell">

                                                <div className="email-avatar">
                                                    {alert.email
                                                        ?.charAt(0)
                                                        ?.toUpperCase() || "U"}
                                                </div>

                                                <div className="email-details">

                                                    <strong>
                                                        {alert.email ||
                                                            "Unknown"}
                                                    </strong>

                                                    <small>
                                                        Security alert
                                                    </small>

                                                </div>

                                            </div>

                                        </td>


                                        {/* ALERT TYPE */}

                                        <td>

                                            <span className="alert-type">

                                                🚨{" "}
                                                {alert.alertType ||
                                                    "Unknown"}

                                            </span>

                                        </td>


                                        {/* MESSAGE */}

                                        <td>

                                            <span className="alert-message">

                                                {alert.message ||
                                                    "—"}

                                            </span>

                                        </td>


                                        {/* SEVERITY */}

                                        <td>

                                            <span
                                                className={`severity ${(
                                                    alert.severity || ""
                                                ).toLowerCase()}`}
                                            >

                                                {alert.severity ||
                                                    "—"}

                                            </span>

                                        </td>


                                        {/* CREATED AT */}

                                        <td>

                                            <div className="created-time">

                                                <strong>

                                                    {alert.createdAt
                                                        ? new Date(
                                                            alert.createdAt
                                                        ).toLocaleDateString()
                                                        : "—"}

                                                </strong>

                                                <small>

                                                    {alert.createdAt
                                                        ? new Date(
                                                            alert.createdAt
                                                        ).toLocaleTimeString()
                                                        : ""}

                                                </small>

                                            </div>

                                        </td>


                                        {/* STATUS */}

                                        <td>

                                            <span className="alert-status">

                                                <span className="status-dot"></span>

                                                {alert.status ||
                                                    "OPEN"}

                                            </span>

                                        </td>

                                    </tr>

                                ))}

                            </tbody>

                        </table>

                    </div>

                )}

            </div>

        </div>
    );
}

export default SecurityAlerts;