services:

  postgres:
    image: postgres:18
    container_name: securevault-postgres
    environment:
      POSTGRES_DB: securevault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build: .
    container_name: securevault-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/securevault
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: unless-stopped

  frontend:
    build: ./secure-vault
    container_name: securevault-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped

volumes:
  postgres_data: