services:
  postgres:
    image: postgres:17
    container_name: securevault-postgres17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - securevault_postgres17_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: securevault-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: securevault-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  securevault_postgres17_data:
    external: true