spring.application.name=PasswordVault

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/password_vault}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8082

# Production session cookie settings
server.servlet.session.cookie.same-site=${SESSION_COOKIE_SAME_SITE:lax}
server.servlet.session.cookie.secure=${SESSION_COOKIE_SECURE:false}

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000