spring.application.name=password-vault-backend

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/password_vault
spring.datasource.username=root
spring.datasource.password=shravya123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bathinishravyagoud@gmail.com
spring.mail.password=cyqxeudinjgrtwne
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=ThisIsASecretKeyForJwtTokensChangeIt12345678901234567890
jwt.expiration=86400000