spring.application.name=backend
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-dry-poetry-a5vsea05-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_N2Cnsyx7Xgez

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ==========================================
# EMAIL CONFIGURATION
# ==========================================

